### ISSUE TITLE
FILEBROWSER_EXTENSIONS not working

### ISSUE THREAD

**Issue by zruu** [stephenmcd/filebrowser-safe#87]
Refering to this issue if this has something to do with it: [https://github.com/sehmaschine/django-filebrowser/issues/307](url)

I still see all the extensions in the admin even if I have set it to:

```
FILEBROWSER_EXTENSIONS = {
    'Image': ['.jpg','.jpeg','.gif','.png','.tif','.tiff'],
}
```

**Comment by ryneeverett** [comment]
I'm not sure why that would be. That should override the default setting [here](https://github.com/stephenmcd/filebrowser-safe/blob/master/filebrowser_safe/settings.py#L51). Are you sure your file field only accepts images? (`FileField(format='Image')`)

**Comment by zruu** [comment]
Yes, I'm sure. Here's a screenshot: [http://imgur.com/a/N1kTt](url)

**Comment by stephenmcd** [comment]
Looking at that line, it looks like the dict for the allowed extensions get updated with whatever's defined in `FILEBROWSER_EXTENSIONS`. So in order to achieve what you want, you need to provide an empty list for each of the existing types, eg:

```
FILEBROWSER_EXTENSIONS = {
    'Image': ['.jpg','.jpeg','.gif','.png','.tif','.tiff'],
    'Video': [],
    'Document': [],
    'Audio': [],
    'Code': []
}
```

I also just pushed 2182a9f7e7ac1980b4ade78e0523a3e62ba3e474 which hides the empty types from the help text.
